"""empty message

Revision ID: 05cfc60c7dd3
Revises: a31550fe34f5
Create Date: 2016-11-18 17:40:26.050000

"""

# revision identifiers, used by Alembic.
revision = '05cfc60c7dd3'
down_revision = 'a31550fe34f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
