"""empty message

Revision ID: 1b94de054d07
Revises: 4d6d2bc86b61
Create Date: 2016-11-18 12:30:17.684000

"""

# revision identifiers, used by Alembic.
revision = '1b94de054d07'
down_revision = '4d6d2bc86b61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
