"""empty message

Revision ID: 22b49ac3e34a
Revises: e594968aab3c
Create Date: 2016-11-12 11:17:55.622000

"""

# revision identifiers, used by Alembic.
revision = '22b49ac3e34a'
down_revision = 'e594968aab3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=32), nullable=False),
    sa.Column('wx_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_table('wx_user')
    ### end Alembic commands ###
