"""empty message

Revision ID: 4d6d2bc86b61
Revises: 922817d0e51b
Create Date: 2016-11-18 12:27:27.745000

"""

# revision identifiers, used by Alembic.
revision = '4d6d2bc86b61'
down_revision = '922817d0e51b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
