"""empty message

Revision ID: 508dc4c1298e
Revises: 4df882e31c8d
Create Date: 2016-11-22 13:38:22.274000

"""

# revision identifiers, used by Alembic.
revision = '508dc4c1298e'
down_revision = '4df882e31c8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'coffee', ['coffee_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'vendor', ['vendor_id'], ['id'])
    op.create_index('idx_demo4_name', 'demo4', [sa.text(u'name DESC')], unique=False)
    op.drop_index('idx_demo3_name', table_name='demo4')
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_index('idx_demo3_name', 'demo4', ['name'], unique=False)
    op.drop_index('idx_demo4_name', table_name='demo4')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
