"""empty message

Revision ID: 59b766c70cce
Revises: 5d9a4d9e329e
Create Date: 2016-11-22 09:53:47.950000

"""

# revision identifiers, used by Alembic.
revision = '59b766c70cce'
down_revision = '5d9a4d9e329e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffee.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_table('coffee_vendor')
    ### end Alembic commands ###
