"""empty message

Revision ID: 5c77675870c6
Revises: 59b766c70cce
Create Date: 2016-11-22 10:06:10.269000

"""

# revision identifiers, used by Alembic.
revision = '5c77675870c6'
down_revision = '59b766c70cce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'coffee', ['coffee_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_table('demo2')
    ### end Alembic commands ###
