"""empty message

Revision ID: 5d2910b52363
Revises: 233c697b6397
Create Date: 2016-11-22 13:50:20.771000

"""

# revision identifiers, used by Alembic.
revision = '5d2910b52363'
down_revision = '233c697b6397'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'coffee', ['coffee_id'], ['id'])
    op.create_foreign_key(None, 'coffee_vendor', 'vendor', ['vendor_id'], ['id'])
    op.create_index('idx_demo5_name_2', 'demo5', ['name'], unique=False)
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index('idx_demo5_name_2', table_name='demo5')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee_vendor', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
