"""empty message

Revision ID: 5d9a4d9e329e
Revises: 2b62644f0e23
Create Date: 2016-11-22 09:52:29.265000

"""

# revision identifiers, used by Alembic.
revision = '5d9a4d9e329e'
down_revision = '2b62644f0e23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_table('demo')
    ### end Alembic commands ###
