"""empty message

Revision ID: 7e40c53c1a70
Revises: cd19dec0040e
Create Date: 2016-11-18 17:35:21.854000

"""

# revision identifiers, used by Alembic.
revision = '7e40c53c1a70'
down_revision = 'cd19dec0040e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
