"""empty message

Revision ID: 922817d0e51b
Revises: e98359da98bc
Create Date: 2016-11-18 12:26:27.428000

"""

# revision identifiers, used by Alembic.
revision = '922817d0e51b'
down_revision = 'e98359da98bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_coffee_name_imported', table_name='coffee')
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.create_index('idx_coffee_name_imported', 'coffee', ['name', 'imported'], unique=False)
    ### end Alembic commands ###
