"""empty message

Revision ID: af09e1841336
Revises: 22b49ac3e34a
Create Date: 2016-11-12 14:32:29.614000

"""

# revision identifiers, used by Alembic.
revision = 'af09e1841336'
down_revision = '22b49ac3e34a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffee', sa.Column('on_sale_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_column('coffee', 'on_sale_date')
    ### end Alembic commands ###
