"""empty message

Revision ID: cd19dec0040e
Revises: d1dc25ff9c4b
Create Date: 2016-11-18 12:31:46.773000

"""

# revision identifiers, used by Alembic.
revision = 'cd19dec0040e'
down_revision = 'd1dc25ff9c4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_coffee_name_imported', 'coffee', ['name', 'imported'], unique=False)
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_index('idx_coffee_name_imported', table_name='coffee')
    ### end Alembic commands ###
