"""empty message

Revision ID: d1dc25ff9c4b
Revises: 3de318b7e29b
Create Date: 2016-11-18 12:30:49.786000

"""

# revision identifiers, used by Alembic.
revision = 'd1dc25ff9c4b'
down_revision = '3de318b7e29b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    ### end Alembic commands ###
