"""empty message

Revision ID: e594968aab3c
Revises: e54d7ce1012f
Create Date: 2016-11-12 10:48:51.999000

"""

# revision identifiers, used by Alembic.
revision = 'e594968aab3c'
down_revision = 'e54d7ce1012f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_table('user')
    ### end Alembic commands ###
