"""empty message

Revision ID: e98359da98bc
Revises: f91e5576c151
Create Date: 2016-11-18 11:32:34.959000

"""

# revision identifiers, used by Alembic.
revision = 'e98359da98bc'
down_revision = 'f91e5576c151'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mountain')
    op.drop_table('article')
    op.drop_table('tag')
    op.drop_table('person')
    op.drop_table('mountain_album')
    op.drop_table('article_tag')
    op.create_index('idx_coffee_name_imported', 'coffee', ['name', 'imported'], unique=False)
    op.create_foreign_key(None, 'coffee', 'vendor', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'coffee', ['coffee_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'coffee', type_='foreignkey')
    op.drop_index('idx_coffee_name_imported', table_name='coffee')
    op.create_table('article_tag',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.create_table('mountain_album',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('mountain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.create_table('person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    op.create_table('mountain',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('altitude', mysql.DECIMAL(precision=11, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    ### end Alembic commands ###
