from .book import Book
from .coffee import Coffee
from .coffee_vendor import coffee_vendor
from .coffee_vendor import demo2
from .demo import Demo
from .demo import Demo3
from .demo import Demo5
from .feedback import Feedback
from .role import Role
from .user import User
from .vendor import Vendor
from .wx_user import WxUser
